on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Release new apk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JAVA
        uses: actions/setup-java@v3
        with:
          distribution: "zulu" # See 'Supported distributions' for available options
          java-version: "17"

      - name: Setup FLUTTER
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Get All Dependencies
        run: flutter pub get

      - name: Build APK File
        run: flutter build apk --release

      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo "$GOOGLE_SERVICES_JSON" > android/app/google-services.json

      - name: Decode firebase_option
        env:
          firebase_options_dart: ${{secrets.FIREBASE_OPTION}}
        run: echo "$firebase_options_dart" > lib/firebase_options.dart

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
          # path: build/app/outputs/apk/debug/app-release.apk

      - name: Move APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
          appId: ${{secrets.APPID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: tester-group
          file: build/app/outputs/apk/release/app-release.apk
          # file: build/app/outputs/apk/debug/app-release.apk

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          # artifacts: "build/app/outputs/apk/debug/*"
          # tag: v0.0.63
          tag: v0.0.${{github.run_number}}
          token: ${{ secrets.REPO_TOKEN }}
